version: "3.8"
services: 
    app:
        build: 
            args: 
                user: hansburnthem
                uid: 1000
            context: ./
            dockerfile: Dockerfile
        image: hnifrma/docker-laravel-str:8.42.2-proxy
        container_name: laravel8-app
        restart: unless-stopped
        working_dir: /var/www/
        volumes: 
            - ./:/var/www
        networks: 
            - default
    
    nginx:
        image: nginx:alpine
        container_name: laravel8-nginx
        restart: unless-stopped
        ports: 
            - 8000:80
        volumes: 
            - ./:/var/www
            - ./config/nginx:/etc/nginx/conf.d/
        networks: 
            - default

networks: 
    default:
        external: true
        name: dbmain