version: "3.8"
services: 
    app:
        build: 
            args: 
                user: hansburnthem
                uid: 1000
            context: ./
            dockerfile: Dockerfile
        image: laravel8
        container_name: testing-app
        restart: unless-stopped
        working_dir: /var/www/
        volumes: 
            - ./:/var/www
        networks: 
            - default
    
    nginx:
        image: nginx:alpine
        container_name: testing-nginx
        restart: unless-stopped
        ports: 
            - 8000:80
        volumes: 
            - ./:/var/www
            - ./docker-compose/nginx:/etc/nginx/conf.d/
        networks: 
            - default

networks: 
    default:
        external: true
        name: dbmain